### ISSUE TITLE
UI localization issues

### ISSUE THREAD

**Issue by CatzMR** [TavstalDev/TShop2#14] opened 2024-08-23 19:02 UTC
The UI font does not seem to support any language other than English. When I use Chinese characters, it will display口
You may need to update https://steamcommunity.com/sharedfiles/filedetails/?id=2767766199.
![image](https://github.com/user-attachments/assets/5da47534-61d0-4f02-9e59-91dc6b61ac91)

**Comment by TavstalDev** [comment] 2024-08-23 19:12
Note to myself:
- Always choose all fonts when installing Linux.
- Always choose all fonts when installing Unity.

(Reference this if it happens again)

**Comment by TavstalDev** [comment] 2024-08-23 20:09
It should be fixed with the latest workshop update.
@CatzMR

**Comment by CatzMR** [comment] 2024-08-24 07:49
> It should be fixed with the latest workshop update. @CatzMR

https://steamcommunity.com/sharedfiles/filedetails/?id=2767766199
I don't quite understand what you mean. It seems that you haven't updated it.

**Comment by TavstalDev** [comment] 2024-08-24 07:58
It seems the upload just disappeared. I have no idea how because I have got the upload successful message from steam.
I am reuploading it now

**Comment by TavstalDev** [comment] 2024-08-24 08:44
So the issue is it literally does not upload the workshop mod but it gives me a success message without any logs to trace what the issue can be. 
Idk when I will be able to update the mod.

**Comment by TavstalDev** [comment] 2024-08-24 10:04
I have successfully uploaded it after nuking steam.  Strange issue.
@CatzMR

**Closed** 2024-08-24 15:45 UTC
Labels: enhancement
